---
platform: linux

image_resource:
  type: registry-image
  source: {repository: vito/oci-build-task}

params:
  REPOSITORY: cirocosta/go-mod-license-finder
  TAG: latest
  CONTEXT: repository

inputs:
- name: repository

outputs:
- name: image

run: {path: build}
