---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

params:
  DIR: ~

inputs:
- name: repo
  path: .
 
outputs:
- name: dependencies

run: 
  path: /bin/sh
  args:
    - -ce
    - |

      if [[ "$DIR" != "" ]]; then
        cd $DIR
      fi

      go mod init || true
      go list -m all > ./dependencies/dependencies.txt
