---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

params:
  DIR: ~

inputs:
- name: repo
  path: .
 
outputs:
- name: dependencies

run: 
  path: /bin/bash
  args:
    - -ce
    - |
      dep_file=$(realpath ./dependencies/dependencies.txt)

      if [[ "$DIR" != "" ]]; then
        cd $DIR
      fi

      go mod init || true
      go list -m all > $dep_file
