---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: repo
  path: .
 
outputs:
- name: dependencies

run: 
  path: /bin/sh
  args:
    - -ce
    - |
      go list -m all > ./dependencies/dependencies.txt
