---
platform: linux

image_resource:
  type: registry-image
  source: {repository: cirocosta/go-mod-dep-source-finder}

inputs:
- name: dependencies
  path: .

run: 
  path: /bin/sh
  args:
    - -ce
    - |
      apk add -qq --update ca-certificates jq
      cat ./dependencies.txt | tail -n +2 | go-mod-dep-source-finder - | jq
