---
platform: linux

image_resource:
  type: registry-image
  source: {repository: cirocosta/go-mod-license-finder}

inputs:
- name: dependencies
  path: .

run: 
  path: /bin/sh
  args:
    - -ce
    - |
      cat ./dependencies.txt | tail -n +2 | go-mod-license-finder -
