resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/go-mod-license-finder

  - name: alpine
    type: registry-image
    source:
      repository: alpine

  - name: golang-alpine
    type: registry-image
    source:
      repository: golang
      tag: alpine

  - name: rc-image
    type: registry-image
    source:
      repository: cirocosta/go-mod-license-finder
      tag: rc
      username: ((docker-user))
      password: ((docker-password))

  - name: final-image
    type: registry-image
    source:
      repository: cirocosta/go-mod-license-finder
      tag: latest
      username: ((docker-user))
      password: ((docker-password))

  - name: concourse-repo
    type: git
    source:
      uri: https://github.com/concourse/concourse

  - name: kubernetes-repo
    type: git
    source:
      uri: https://github.com/kubernetes/kubernetes

  - name: sourcegraph-repo
    type: git
    source:
      uri: https://github.com/sourcegraph/sourcegraph

  - name: prometheus-repo
    type: git
    source:
      uri: https://github.com/prometheus/prometheus


jobs:
  - name: build
    public: true
    serial: true
    plan:
      - aggregate:
        - get: alpine
          trigger: true
        - get: golang-alpine
          trigger: true
        - get: repository
          trigger: true
      - task: build-image
        privileged: true
        file: repository/ci/tasks/build-image.yml
      - put: rc-image
        inputs: [image]
        get_params: {format: oci}
        params: {image: image/image.tar}

  - name: concourse-deps
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          passed: [build]
          trigger: true
        - get: rc-image
          passed: [build]
          trigger: true
        - get: concourse-repo
          trigger: true
      - task: gather-dependencies
        input_mapping: {repo: concourse-repo}
        file: repository/ci/tasks/gather-dependencies-list.yml
      - task: execute
        image: rc-image
        file: repository/ci/tasks/resolve-deps.yml

  - name: kubernetes-deps
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          passed: [build]
          trigger: true
        - get: rc-image
          passed: [build]
          trigger: true
        - get: kubernetes-repo
          trigger: true
      - task: gather-dependencies
        input_mapping: {repo: kubernetes-repo}
        file: repository/ci/tasks/gather-dependencies-list.yml
      - task: execute
        image: rc-image
        file: repository/ci/tasks/resolve-deps.yml


  - name: sourcegraph-deps
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          passed: [build]
          trigger: true
        - get: rc-image
          passed: [build]
          trigger: true
        - get: sourcegraph-repo
          trigger: true
      - task: gather-dependencies
        input_mapping: {repo: sourcegraph-repo}
        file: repository/ci/tasks/gather-dependencies-list.yml
      - task: execute
        image: rc-image
        file: repository/ci/tasks/resolve-deps.yml


  - name: prometheus-deps
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          passed: [build]
          trigger: true
        - get: rc-image
          passed: [build]
          trigger: true
        - get: prometheus-repo
          trigger: true
      - task: gather-dependencies
        input_mapping: {repo: prometheus-repo}
        file: repository/ci/tasks/gather-dependencies-list.yml
      - task: execute
        image: rc-image
        file: repository/ci/tasks/resolve-deps.yml

  - name: publish-image
    public: true
    serial: true
    plan:
      - get: rc-image
        params: {format: oci}
        passed: [concourse-deps,prometheus-deps,sourcegraph-deps,kubernetes-deps]
        trigger: true
      - put: final-image
        params: {image: rc-image/image.tar}
