resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/go-mod-license-finder

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/go-mod-license-finder
      username: ((docker-user))
      password: ((docker-password))

  - name: concourse-repo
    type: git
    source:
      uri: https://github.com/concourse/concourse

  - name: kubernetes-repo
    type: git
    source:
      uri: https://github.com/kubernetes/kubernetes


jobs:
  - name: build
    public: true
    serial: true
    plan:
      - get: repository
        trigger: true
      - task: build-image
        privileged: true
        file: repository/ci/tasks/build-image.yml
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params: {image: image/image.tar}

  - name: concourse-deps
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          passed: [build]
          trigger: true
        - get: container-image
          passed: [build]
          trigger: true
        - get: concourse-repo
          trigger: true
      - task: gather-dependencies
        input_mapping: {repo: concourse-repo}
        file: repository/ci/tasks/gather-dependencies-list.yml
      - task: execute
        image: container-image
        file: repository/ci/tasks/resolve-concourse-deps.yml

  - name: kubernetes-deps
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          passed: [build]
          trigger: true
        - get: container-image
          passed: [build]
          trigger: true
        - get: kubernetes-repo
          trigger: true
      - task: gather-dependencies
        input_mapping: {repo: concourse-repo}
        file: repository/ci/tasks/gather-dependencies-list.yml
      - task: execute
        image: container-image
        file: repository/ci/tasks/resolve-concourse-deps.yml
